include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"
  - project: "smartive/ci-templates"
    ref: v4.0.0
    file: "/all-templates.yml"

stages:
  - test
  - release

.default_template:
  extends: .base
  image: node:16

.test_template:
  extends: .default_template
  stage: test
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - npm ci

linting:
  extends: .test_template
  script:
    - npm run lint
  only:
    - merge_requests

tests:
  extends: .test_template
  script:
    - cd apps/website
    - npm run test:ci
  only:
    - merge_requests

publish:
  extends: .default_template
  stage: release
  before_script:
    - npm ci
  script:
    - npm run publish
  only:
    - main
