include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"
  - project: "smartive/ci-templates"
    ref: v4.0.0
    file: "/all-templates.yml"

.default_template:
  extends: .base
  image: node:16-alpine

.test_template:
  extends: .default_template
  stage: test
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - npm ci

.deploy_template:
  extends: .default_template
  stage: deploy
  before_script:
    - cd apps/website
    - npm i -g vercel

linting:
  extends: .test_template
  script:
    - npm run lint

tests:
  extends: .test_template
  script:
    - cd apps/website
    - npm run test:ci

test build:
  extends: .test_template
  script:
    - npm run build
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate\//'

deploy preview:
  extends: .deploy_template
  script:
    - vercel --token $VERCEL_TOKEN --confirm --scope smartive
  rules:
    - if: '$CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate\//'

deploy production:
  extends: .deploy_template
  script:
    - vercel --token $VERCEL_TOKEN --confirm --scope smartive --prod
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
