include:
  - project: 'smartive/ci-templates'
    ref: v4.0.0
    file: '/all-templates.yml'
  - project: 'smartive/ci-templates'
    ref: 4.x
    file: '/renovate/default-trigger.yml'

stages:
  - test

.default_template:
  extends: .base
  image: node
  before_script:
    - npm ci

.test_template:
  extends: .default_template
  stage: test
  except:
    - tags

lint:
  extends: .test_template
  script:
    - npm run lint
    - npm run check
