include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: 'smartive/ci-templates'
    ref: v4.0.0
    file: '/all-templates.yml'

stages:
  - test
  - release
  - deploy

.default_template:
  extends: .base
  image: node:16-alpine

.test_template:
  extends: .default_template
  stage: test
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - npm ci

.deploy_template:
  extends: .default_template
  stage: deploy
  before_script:
    - npm ci
    - npm i -g vercel

linting:
  extends: .test_template
  script:
    - npm run lint
  only:
    - merge_requests

tests:
  extends: .test_template
  script:
    - npm run test:ci
  only:
    - merge_requests

deploy preview:
  extends: .deploy_template
  script:
    - npm run deploy:preview
  rules:
    - if: '$CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate\//'

deploy production:
  extends: .deploy_template
  script:
    - npm run deploy:production
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
